/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Kris
 */
public class Departments extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeRegister
     */
    public Departments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        btn_newDept = new javax.swing.JPanel();
        txt_btn_newDept = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(ColorScheme.SetColor.COSMIC_LATE);
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Departamentos");

        btn_newDept.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_newDept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_newDept.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_newDept.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_newDept.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_newDept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_newDept.setText("Nuevo departamento");
        txt_btn_newDept.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout btn_newDeptLayout = new javax.swing.GroupLayout(btn_newDept);
        btn_newDept.setLayout(btn_newDeptLayout);
        btn_newDeptLayout.setHorizontalGroup(
            btn_newDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_newDeptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_btn_newDept, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_newDeptLayout.setVerticalGroup(
            btn_newDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_btn_newDept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setBackground(ColorScheme.SetColor.DESERT_SAND);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setForeground(ColorScheme.SetColor.UMBER);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad de empleados", "Asistencia promedio", "Tareas completadas", "Administrar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(ColorScheme.SetColor.EGGSHELL);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addComponent(lbl_moduleName))
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeRegisterContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_newDept, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        EmployeeRegisterContainerLayout.setVerticalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_moduleName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_newDept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JPanel btn_newDept;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JLabel txt_btn_newDept;
    // End of variables declaration//GEN-END:variables
}
