/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Kris
 */
public class FindEmployee extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeRegister
     */
    public FindEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        btn_filter = new javax.swing.JPanel();
        txt_btn_filter = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(ColorScheme.SetColor.COSMIC_LATE);
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Busqueda de empleados");

        btn_filter.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_filter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_filter.setPreferredSize(new java.awt.Dimension(150, 35));

        javax.swing.GroupLayout btn_filterLayout = new javax.swing.GroupLayout(btn_filter);
        btn_filter.setLayout(btn_filterLayout);
        btn_filterLayout.setHorizontalGroup(
            btn_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        btn_filterLayout.setVerticalGroup(
            btn_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        txt_btn_filter.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_filter.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_filter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_filter.setText("Filtrar");
        txt_btn_filter.setPreferredSize(new java.awt.Dimension(70, 30));

        jComboBox1.setBackground(ColorScheme.SetColor.EGGSHELL);
        jComboBox1.setForeground(ColorScheme.SetColor.DESERT_SAND);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salario:" }));
        jComboBox1.setBorder(null);
        jComboBox1.setPreferredSize(new java.awt.Dimension(120, 30));

        jComboBox2.setBackground(ColorScheme.SetColor.DESERT_SAND);
        jComboBox2.setForeground(ColorScheme.SetColor.DESERT_SAND);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo:" }));
        jComboBox2.setBorder(null);
        jComboBox2.setPreferredSize(new java.awt.Dimension(120, 30));

        jTable1.setBackground(ColorScheme.SetColor.DESERT_SAND);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setForeground(ColorScheme.SetColor.UMBER);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Departamento", "Cargo", "Asistencia promedio", "Tareas completadas", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(ColorScheme.SetColor.EGGSHELL);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                            .addComponent(lbl_moduleName))))
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txt_btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        EmployeeRegisterContainerLayout.setVerticalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_moduleName)
                .addGap(9, 9, 9)
                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_btn_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JPanel btn_filter;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JLabel txt_btn_filter;
    // End of variables declaration//GEN-END:variables
}
