package GUI.Modules;

import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;

import java.awt.event.MouseEvent;

import Classes.Department;
import ComponentMaintainer.*;
import GUI.MainModules.Login;

/**
 * @author Kris
 */
public class Departments extends javax.swing.JPanel {

    DatabaseConection dbc = Login.dbc;
    public static String departmentName;

    /**
     * Creates new form EmployeeRegister
     */
    public Departments() {
        initComponents();

        CreateModel();

        showDepartments(dbc.connection);

        GetTableCellClick();
    }

    private void showDepartments(Connection dbConnection) {
        Object O[] = null;
        String query = "SELECT name FROM departments ORDER BY name ASC";

        try (PreparedStatement stmt = dbConnection.prepareStatement(query)) {

            try (ResultSet rs = stmt.executeQuery()) {
                int i = 0;
                Department dept = new Department();
                while (rs.next()) {
                    dept.setName(rs.getString("name"));
                    model.addRow(O);
                    model.setValueAt(dept.getName(), i, 0);
                    model.setValueAt(("Administrar " + dept.getName()).toUpperCase(), i, 1);
                    i++;
                }
            }
            catch (SQLException sqle) {
                sqle.printStackTrace();
            }
        }
        catch (SQLException sqle) {
            sqle.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        btn_newDept = new javax.swing.JPanel();
        txt_btn_newDept = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE));
        jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE));

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(CM_Color.Background());
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setForeground(CM_Color.Text());
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Departamentos");

        btn_newDept.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_newDept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_newDept.setPreferredSize(new java.awt.Dimension(150, 35));
        btn_newDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newDeptMouseClicked(evt);
            }
        });

        txt_btn_newDept.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_newDept.setForeground(CM_Color.Text());
        txt_btn_newDept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_newDept.setText("Nuevo departamento");
        txt_btn_newDept.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout btn_newDeptLayout = new javax.swing.GroupLayout(btn_newDept);
        btn_newDept.setLayout(btn_newDeptLayout);
        btn_newDeptLayout.setHorizontalGroup(btn_newDeptLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_newDeptLayout.createSequentialGroup().addContainerGap()
                        .addComponent(txt_btn_newDept, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addContainerGap()));
        btn_newDeptLayout.setVerticalGroup(
                btn_newDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        txt_btn_newDept, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        jTable1.setBackground(CM_Color.Button());
        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setForeground(CM_Color.Text());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] {

        }));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(ColorScheme.SetColor.EGGSHELL);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(
                EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(
                EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(37, 37, 37)
                                .addGroup(EmployeeRegisterContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908,
                                                Short.MAX_VALUE)
                                        .addComponent(lbl_moduleName))
                                .addGap(135, 135, 135))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                EmployeeRegisterContainerLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_newDept, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)));
        EmployeeRegisterContainerLayout.setVerticalGroup(
                EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(27, 27, 27)
                                .addComponent(lbl_moduleName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_newDept, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE)));

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newDeptMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_newDeptMouseClicked
        CM_Views.DepartmentsModule.NewDepartment().setVisible(true);
    }// GEN-LAST:event_btn_newDeptMouseClicked

    DefaultTableModel model;

    private void CreateModel() {
        try {
            model = (new DefaultTableModel(null, new String[] {
                    "Nombre", "Administrar" }) {
                @SuppressWarnings("rawtypes")
                Class[] types = new Class[] {
                        java.lang.String.class, java.lang.String.class };
                boolean[] canEdit = new boolean[] {
                        false, false };

                @SuppressWarnings({
                        "rawtypes", "unchecked" })
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            jTable1.setModel(model);
        }
        catch (Exception e) {
            System.err.println("No se pudo crear la tabla " + e);
        }

    }

    public void GetTableCellClick() {
        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int column = jTable1.columnAtPoint(evt.getPoint());
                int deptOptions = 1;

                if (column == deptOptions) {
                    departmentName = (String) model.getValueAt(row, column-1);
                    CM_Views.DepartmentsModule.EditDepartment().setVisible(true);
                    System.err.println(departmentName);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JPanel btn_newDept;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JLabel txt_btn_newDept;
    // End of variables declaration//GEN-END:variables
}
