package GUI.Modules;

import Classes.User;

import ComponentMaintainer.CM_Color;
import ComponentMaintainer.DatabaseConection;

import GUI.MainModules.Login;

/**
 * @author Kris
 */
public class EmployeeProfile extends javax.swing.JPanel {

        public static User employee = Login.actualSession;
        DatabaseConection dbc = Login.dbc;

        /**
         * Creates new form EmployeeRegister
         */
        public EmployeeProfile() {
                initComponents();

                employee.SeeInfo(employee.getId(), dbc.connection);
                txt_name.setText(employee.getName());
                txt_address.setText(employee.getAddress());
                txt_birthday.setText(employee.getBirthDay());
                txt_phoneNumber.setText(employee.getPhoneNumber());
                txt_email.setText(employee.getEmail());
                txt_position.setText(employee.getPosition());
                txt_password.setText(employee.getPassword());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        nameContainer = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        addressContainer = new javax.swing.JPanel();
        txt_address = new javax.swing.JTextField();
        birthdayContainer = new javax.swing.JPanel();
        txt_birthday = new javax.swing.JTextField();
        email_Container = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        position_Container = new javax.swing.JPanel();
        txt_position = new javax.swing.JTextField();
        phoneNumberContainer = new javax.swing.JPanel();
        txt_phoneNumber = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btn_save = new javax.swing.JPanel();
        txt_btn_save = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        password_Container = new javax.swing.JPanel();
        txt_password = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(CM_Color.Background());
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setForeground(CM_Color.Text());
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Perfil de empleado");

        nameContainer.setBackground(CM_Color.Button());
        nameContainer.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_name.setBackground(CM_Color.Button());
        txt_name.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_name.setForeground(CM_Color.CloseButtonHover());
        txt_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_name.setBorder(null);
        txt_name.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout nameContainerLayout = new javax.swing.GroupLayout(nameContainer);
        nameContainer.setLayout(nameContainerLayout);
        nameContainerLayout.setHorizontalGroup(
            nameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        nameContainerLayout.setVerticalGroup(
            nameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        addressContainer.setBackground(CM_Color.Button());
        addressContainer.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_address.setBackground(CM_Color.Button());
        txt_address.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_address.setForeground(CM_Color.CloseButtonHover());
        txt_address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_address.setBorder(null);
        txt_address.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout addressContainerLayout = new javax.swing.GroupLayout(addressContainer);
        addressContainer.setLayout(addressContainerLayout);
        addressContainerLayout.setHorizontalGroup(
            addressContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addressContainerLayout.setVerticalGroup(
            addressContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        birthdayContainer.setBackground(CM_Color.Button());
        birthdayContainer.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_birthday.setBackground(CM_Color.Button());
        txt_birthday.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_birthday.setForeground(CM_Color.CloseButtonHover());
        txt_birthday.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_birthday.setBorder(null);
        txt_birthday.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout birthdayContainerLayout = new javax.swing.GroupLayout(birthdayContainer);
        birthdayContainer.setLayout(birthdayContainerLayout);
        birthdayContainerLayout.setHorizontalGroup(
            birthdayContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdayContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        birthdayContainerLayout.setVerticalGroup(
            birthdayContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, birthdayContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        email_Container.setBackground(CM_Color.Button());
        email_Container.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_email.setBackground(CM_Color.Button());
        txt_email.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_email.setForeground(CM_Color.CloseButtonHover());
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setBorder(null);
        txt_email.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout email_ContainerLayout = new javax.swing.GroupLayout(email_Container);
        email_Container.setLayout(email_ContainerLayout);
        email_ContainerLayout.setHorizontalGroup(
            email_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(email_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        email_ContainerLayout.setVerticalGroup(
            email_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, email_ContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        position_Container.setBackground(CM_Color.Button());
        position_Container.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_position.setBackground(ColorScheme.SetColor.DESERT_SAND);
        txt_position.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_position.setForeground(CM_Color.CloseButtonHover());
        txt_position.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_position.setBorder(null);
        txt_position.setEnabled(false);
        txt_position.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout position_ContainerLayout = new javax.swing.GroupLayout(position_Container);
        position_Container.setLayout(position_ContainerLayout);
        position_ContainerLayout.setHorizontalGroup(
            position_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(position_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_position, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        position_ContainerLayout.setVerticalGroup(
            position_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, position_ContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        phoneNumberContainer.setBackground(CM_Color.Button());
        phoneNumberContainer.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_phoneNumber.setBackground(CM_Color.Button());
        txt_phoneNumber.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_phoneNumber.setForeground(CM_Color.CloseButtonHover());
        txt_phoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_phoneNumber.setBorder(null);
        txt_phoneNumber.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout phoneNumberContainerLayout = new javax.swing.GroupLayout(phoneNumberContainer);
        phoneNumberContainer.setLayout(phoneNumberContainerLayout);
        phoneNumberContainerLayout.setHorizontalGroup(
            phoneNumberContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        phoneNumberContainerLayout.setVerticalGroup(
            phoneNumberContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phoneNumberContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        btn_save.setBackground(CM_Color.Button());
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_save.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_save.setForeground(CM_Color.Text());
        txt_btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_save.setText("Guardar");
        txt_btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_btn_saveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_saveLayout = new javax.swing.GroupLayout(btn_save);
        btn_save.setLayout(btn_saveLayout);
        btn_saveLayout.setHorizontalGroup(
            btn_saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btn_saveLayout.setVerticalGroup(
            btn_saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre");

        jLabel2.setText("Dirección");

        jLabel3.setText("Fecha de nacimiento (AAAA-MM-DD)");

        jLabel4.setText("Numero telefonico");

        jLabel5.setText("Email");

        password_Container.setBackground(CM_Color.Button());
        password_Container.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_password.setBackground(CM_Color.Button());
        txt_password.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_password.setForeground(CM_Color.CloseButtonHover());
        txt_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_password.setBorder(null);
        txt_password.setPreferredSize(new java.awt.Dimension(245, 30));

        javax.swing.GroupLayout password_ContainerLayout = new javax.swing.GroupLayout(password_Container);
        password_Container.setLayout(password_ContainerLayout);
        password_ContainerLayout.setHorizontalGroup(
            password_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        password_ContainerLayout.setVerticalGroup(
            password_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, password_ContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel6.setText("Contraseña");

        jLabel7.setText("Cargo");

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(position_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbl_moduleName))
                            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                                        .addComponent(jSeparator2)
                                        .addComponent(addressContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator5)
                                        .addComponent(birthdayContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                                        .addComponent(jSeparator4))
                                    .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))))))
                        .addComponent(password_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)))
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        EmployeeRegisterContainerLayout.setVerticalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_moduleName)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(nameContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthdayContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(position_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
// </editor-fold>                        
// </editor-fold>                        

        private void txt_btn_saveMouseClicked(java.awt.event.MouseEvent evt) {
                User uio = new User(employee.getId(),
                                txt_name.getText(),
                                txt_address.getText(),
                                txt_birthday.getText(),
                                txt_phoneNumber.getText(),
                                txt_email.getText(),
                                txt_position.getText(),
                                employee.getSalary(),
                                txt_password.getText(),
                                employee.getCheckinHour(),
                                employee.getCheckoutHour(),
                                employee.getDepartment(),
                                employee.getIsAdmin());

                uio.UpdateInfo(dbc.connection);

        }// GEN-LAST:event_txt_btn_saveMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JPanel addressContainer;
    private javax.swing.JPanel birthdayContainer;
    private javax.swing.JPanel btn_save;
    private javax.swing.JPanel email_Container;
    private javax.swing.JPanel email_Container1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JPanel nameContainer;
    private javax.swing.JPanel password_Container;
    private javax.swing.JPanel phoneNumberContainer;
    private javax.swing.JPanel position_Container;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_birthday;
    private javax.swing.JLabel txt_btn_save;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_position;
    // End of variables declaration//GEN-END:variables
}
