package GUI.Modules;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;

import ComponentMaintainer.CM_Color;

import GUI.MainModules.Login;

/**
 * @author Kris
 */
public class GeneralReports extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeRegister
     */
    public GeneralReports() {
        initComponents();
        CreateModels();
        getTableInformation(Login.dbc.connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_employeeReport = new javax.swing.JTable();
        scrollDept = new javax.swing.JScrollPane();
        table_deptReport = new javax.swing.JTable();
        lbl_employeeReport = new javax.swing.JLabel();
        lbl_deptReport = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(CM_Color.Background());
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setForeground(CM_Color.Text());
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Reportes");

        table_employeeReport.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] {
                "Nombre", "Promedio de asistencia", "Tareas completadas" }));
        jScrollPane1.setViewportView(table_employeeReport);

        table_deptReport.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
                {
                        null, null },
                {
                        null, null },
                {
                        null, null },
                {
                        null, null } },
                new String[] {
                        "Nombre", "Empleados en el departamento" }));
        scrollDept.setViewportView(table_deptReport);

        lbl_employeeReport.setText("Empleados");

        lbl_deptReport.setText("Departamentos");

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(
                EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(EmployeeRegisterContainerLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(37, 37, 37)
                        .addGroup(EmployeeRegisterContainerLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51).addComponent(scrollDept,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_moduleName))
                        .addContainerGap(88, Short.MAX_VALUE))
                .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(212, 212, 212)
                        .addComponent(lbl_employeeReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_deptReport).addGap(291, 291, 291)));
        EmployeeRegisterContainerLayout.setVerticalGroup(EmployeeRegisterContainerLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(27, 27, 27)
                        .addComponent(lbl_moduleName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(EmployeeRegisterContainerLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_employeeReport).addComponent(lbl_deptReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EmployeeRegisterContainerLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrollDept, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)));

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
     // </editor-fold>

    DefaultTableModel modelEmployeeReporTableModel;
    DefaultTableModel modelDeptReportTableModel;

    private void CreateModels() {
        // modelEmployeeReporTableModel
        try {
            modelEmployeeReporTableModel = (new DefaultTableModel(null, new String[]{
                "Nombre", "Promedio de asistencia", "Tareas completadas"}) {

                @SuppressWarnings("rawtypes")
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.Integer.class};

                boolean[] canEdit = new boolean[]{
                    false, false, false};

                @SuppressWarnings({
                    "rawtypes", "unchecked"})
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });

            modelDeptReportTableModel = (new DefaultTableModel(null, new String[]{
                "Nombre", "Empleados en el departamento"}) {

                @SuppressWarnings("rawtypes")
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.Integer.class};

                boolean[] canEdit = new boolean[]{
                    false, false};

                @SuppressWarnings({
                    "rawtypes", "unchecked"})
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });

            table_employeeReport.setModel(modelEmployeeReporTableModel);
            table_deptReport.setModel(modelDeptReportTableModel);
        } catch (Exception e) {
            System.err.println("Error al crear las tablas " + e);
        }
    }

    private void getTableInformation(Connection dbConnection) {
        Object Obj1[] = null;
        Object Obj2[] = null;

        String employeeInfoQuery = "SELECT usr_name FROM users";
        String deptInfoQuery = "SELECT dept_name FROM departments";

        int employeeCount = 0;
        int deptCount = 0;

        try (PreparedStatement eiPstmt = dbConnection.prepareStatement(employeeInfoQuery); PreparedStatement diPstmt = dbConnection.prepareStatement(deptInfoQuery)) {
            try (ResultSet eiRs = eiPstmt.executeQuery(); ResultSet diRs = diPstmt.executeQuery()) {
                while (eiRs.next()) {
                    modelEmployeeReporTableModel.addRow(Obj1);
                    modelEmployeeReporTableModel.setValueAt(eiRs.getString("usr_name"), employeeCount, 0);
                    modelEmployeeReporTableModel.setValueAt("promedio de asistencia", employeeCount, 1);
                    // TODO Get the completed tasks
                    modelEmployeeReporTableModel.setValueAt(0, employeeCount, 2);
                    employeeCount++;
                }
                while (diRs.next()) {
                    modelDeptReportTableModel.addRow(Obj2);
                    modelDeptReportTableModel.setValueAt(diRs.getString("dept_name"), deptCount, 0);
                    
                    modelDeptReportTableModel.setValueAt(0, deptCount, 1);
                    deptCount++;
                }
            }
        } catch (SQLException sqle) {
            System.err.println(sqle);
        }
        modelEmployeeReporTableModel.addRow(Obj1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_deptReport;
    private javax.swing.JLabel lbl_employeeReport;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JScrollPane scrollDept;
    private javax.swing.JTable table_deptReport;
    private javax.swing.JTable table_employeeReport;
    // End of variables declaration//GEN-END:variables
}
