package GUI.Modules;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;

import Classes.Project;

import ComponentMaintainer.CM_Views;
import ComponentMaintainer.CM_Color;

import GUI.MainModules.Login;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author Kris
 */
public class Projects extends javax.swing.JPanel {

    public static String[] status = {
        "sin comenzar", "postpuesta", "en curso", "finalizada"};
    public static int projectid;
    public static int taskid;
    public static String taskData;
    public static String projectData;

    /**
     * Creates new form EmployeeRegister
     */
    public Projects() {
        initComponents();

        CreateModel();

        GetTableCellClick(Login.dbc.connection);

        showProjects(Login.dbc.connection);
    }

    private void showProjects(Connection dbConnection) {
        Object O[] = null;
        String projectQuery = "SELECT * FROM projects ORDER BY proj_name ASC";
        String deptQuery = "SELECT dept_name FROM departments where dept_id = ?";

        try (PreparedStatement proj_stmt = dbConnection.prepareStatement(projectQuery)) {

            try (ResultSet rs = proj_stmt.executeQuery()) {
                int i = 0;
                Project proj = new Project();

                while (rs.next()) {

                    proj.setName(rs.getString("proj_name"));
                    proj.setStatus(rs.getString("proj_status"));
                    proj.setDueDate(rs.getString("proj_deadline"));
                    proj.setCompletedTasks(rs.getInt("proj_completedTasks"));
                    proj.setTotalTasks(rs.getInt("proj_totalTasks"));

                    // Get the project's department
                    PreparedStatement projdept_stmt = dbConnection.prepareStatement(deptQuery);
                    projdept_stmt.setString(1, rs.getString("proj_assignedDepartment"));
                    ResultSet projdept_rs = projdept_stmt.executeQuery();

                    if (projdept_rs.next()) {
                        proj.setAssignedDept(projdept_rs.getString("dept_name"));
                    }

                    model.addRow(O);
                    model.setValueAt(proj.getName(), i, 0);
                    model.setValueAt(proj.getAssignedDept(), i, 1);
                    model.setValueAt(proj.getCompletedTasks() + " / " + proj.getTotalTasks(), i, 2);
                    model.setValueAt(proj.getStatus(), i, 3);
                    model.setValueAt(proj.getDueDate(), i, 4);
                    model.setValueAt("Información de " + proj.getName(), i, 5);
                    model.setValueAt("Información de proyecto: " + proj.getName(), i, 5);

                    i++;
                }
            } catch (SQLException sqle) {
                sqle.printStackTrace();
            }
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        btn_newTask = new javax.swing.JPanel();
        txt_btn_newTasks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_newProject = new javax.swing.JPanel();
        txt_btn_newProject = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE));
        jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE));

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(CM_Color.Background());
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setForeground(CM_Color.Text());
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Proyectos");

        btn_newTask.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_newTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_newTask.setPreferredSize(new java.awt.Dimension(150, 35));
        btn_newTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newTaskMouseClicked(evt);
            }
        });

        txt_btn_newTasks.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_newTasks.setForeground(CM_Color.Text());
        txt_btn_newTasks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_newTasks.setText("Nueva tarea");
        txt_btn_newTasks.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout btn_newTaskLayout = new javax.swing.GroupLayout(btn_newTask);
        btn_newTask.setLayout(btn_newTaskLayout);
        btn_newTaskLayout.setHorizontalGroup(btn_newTaskLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_newTaskLayout.createSequentialGroup().addContainerGap()
                        .addComponent(txt_btn_newTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addContainerGap()));
        btn_newTaskLayout.setVerticalGroup(
                btn_newTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        txt_btn_newTasks, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        jTable1.setBackground(CM_Color.Button());
        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setForeground(CM_Color.Text());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] {

        }));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(ColorScheme.SetColor.EGGSHELL);
        jScrollPane1.setViewportView(jTable1);

        btn_newProject.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_newProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_newProject.setPreferredSize(new java.awt.Dimension(150, 35));
        btn_newProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newProjectMouseClicked(evt);
            }
        });

        txt_btn_newProject.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_newProject.setForeground(CM_Color.Text());
        txt_btn_newProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_newProject.setText("Nuevo proyecto");
        txt_btn_newProject.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout btn_newProjectLayout = new javax.swing.GroupLayout(btn_newProject);
        btn_newProject.setLayout(btn_newProjectLayout);
        btn_newProjectLayout.setHorizontalGroup(btn_newProjectLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_newProjectLayout.createSequentialGroup().addContainerGap()
                        .addComponent(txt_btn_newProject, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addContainerGap()));
        btn_newProjectLayout.setVerticalGroup(
                btn_newProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        txt_btn_newProject, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(
                EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(
                EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(37, 37, 37)
                                .addGroup(EmployeeRegisterContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908,
                                                Short.MAX_VALUE)
                                        .addComponent(lbl_moduleName))
                                .addGap(135, 135, 135))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                EmployeeRegisterContainerLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_newProject, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_newTask, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)));
        EmployeeRegisterContainerLayout.setVerticalGroup(
                EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup().addGap(27, 27, 27)
                                .addComponent(lbl_moduleName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(EmployeeRegisterContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_newTask, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_newProject, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE)));

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newProjectMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_newProjectMouseClicked
        CM_Views.ProjectsModule.NewProject().setVisible(true);
    }// GEN-LAST:event_btn_newProjectMouseClicked

    private void btn_newTaskMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_newTaskMouseClicked
        CM_Views.ProjectsModule.NewTask().setVisible(true);
    }// GEN-LAST:event_btn_newTaskMouseClicked
    // </editor-fold>

    DefaultTableModel model;

    private void CreateModel() {
        try {
            model = (new DefaultTableModel(null, new String[]{
                "Nombre", "Departamento encargado", "tareas completadas", "Estado", "Fecha limite", "ver tareas",
                "editar proyecto"}) {
                @SuppressWarnings("rawtypes")
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class};
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false};

                @SuppressWarnings({
                    "rawtypes", "unchecked"})
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            jTable1.setModel(model);
        } catch (Exception e) {
            System.err.println("No se pudo crear la tabla " + e);
        }

    }

    public void GetTableCellClick(Connection dbConnection) {

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int column = jTable1.columnAtPoint(evt.getPoint());
                int taskcolumn = 5;
                int projectColumn = 6;

                if (column == taskcolumn) {
                    taskData = (String) model.getValueAt(row, 0);
                    CM_Views.ProjectsModule.TaskList().setVisible(true);
                }
                if (column == projectColumn) {
                    projectData = (String) model.getValueAt(row, 0);
                    CM_Views.ProjectsModule.EditProject().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JPanel btn_newProject;
    private javax.swing.JPanel btn_newTask;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JLabel txt_btn_newProject;
    private javax.swing.JLabel txt_btn_newTasks;
    // End of variables declaration//GEN-END:variables
}
